#!/usr/bin/env python3
"""Record the layout ground-truth corpus in one scripted device session.

Phase 2 of the layout test bench (see ``docs/LAYOUT_TESTBENCH_PLAN.md``). This
tool automates everything around the single device session so that the operator
only has to highlight sentinel words and draw one probe stroke:

    1. PUSH   - sync the calibration markdown suite
                (``tests/record_replay/testdata/calibration/<device>/src/``) to
                the device using the production ``rock-paper-sync sync`` CLI.
    2. ANNOTATE - print an operator checklist ("highlight every ZEBRAnn token,
                draw the T5 descender stroke") and wait.
    3. PULL   - download the resulting ``.rm`` files from the cloud and the page
                thumbnails via SSH, then stamp firmware / xochitl version and
                recording date into ``profile.json``.

After this runs, ``extract_profile.py`` turns the pulled ``.rm`` files into
measured layout values. The device is a data source, not a test loop (P1): run
this once per device model / firmware and iterate locally thereafter.

Usage:
    # Full session (push, wait for annotations, pull):
    uv run python tools/calibration/record_corpus.py --device-host remarkable-ppm

    # Skip the push (documents already on device) and go straight to pull:
    uv run python tools/calibration/record_corpus.py --skip-push

    # Push only, then stop (annotate later, pull in a second invocation):
    uv run python tools/calibration/record_corpus.py --push-only

Requires:
    - Configured cloud credentials (``rock-paper-sync init`` / ``register``).
    - SSH access to the device (root@<device-host>) for thumbnails + firmware.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# Repo root and imports -----------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT / "tools"))

# Reuse the existing device-capture helpers rather than reimplementing them.
from analysis.device_capture import (  # noqa: E402
    Colors,
    capture_thumbnails_via_ssh,
    download_rm_files,
    find_document,
    get_cloud_client,
    print_error,
    print_ok,
    print_step,
    print_warn,
)

DEFAULT_DEVICE = "paper_pro_move"
CORPUS_ROOT = REPO_ROOT / "tests" / "record_replay" / "testdata" / "calibration"
DEFAULT_DEVICE_FOLDER = "LayoutCalibration"


def corpus_dir(device: str) -> Path:
    return CORPUS_ROOT / device


def src_dir(device: str) -> Path:
    return corpus_dir(device) / "src"


def corpus_documents(device: str) -> list[str]:
    """Return the document names (markdown stems) in the corpus, sorted."""
    return sorted(p.stem for p in src_dir(device).glob("*.md") if p.name != "README.md")


# --- Step 1: push ----------------------------------------------------------


def write_push_config(config_file: Path, device: str, device_folder: str, cloud_base_url: str) -> None:
    """Write a temporary config whose single vault is the corpus src/ dir."""
    workspace = config_file.parent
    state_dir = workspace / ".state"
    cache_dir = workspace / ".cache"
    log_dir = workspace / "logs"
    for d in (state_dir, cache_dir, log_dir):
        d.mkdir(parents=True, exist_ok=True)

    config = f"""# Layout calibration corpus push config (generated by record_corpus.py)
[cloud]
base_url = "{cloud_base_url}"

[paths]
state_database = "{state_dir}/state.db"
cache_dir = "{cache_dir}"

[logging]
level = "debug"
file = "{log_dir}/sync.log"

[ocr]
enabled = false
provider = "none"

[[vaults]]
name = "layout-calibration"
path = "{src_dir(device)}"
remarkable_folder = "{device_folder}"
include_patterns = ["**/*.md"]
exclude_patterns = ["README.md"]
"""
    config_file.write_text(config)


def push_corpus(device: str, device_folder: str, user_config: Path) -> None:
    """Push the corpus markdown suite to the device via the production CLI."""
    from rock_paper_sync.config import load_config

    print_step("Pushing calibration corpus to device")

    if not user_config.exists():
        print_error(f"User config not found: {user_config}")
        print_error("Run: uv run rock-paper-sync init")
        sys.exit(1)

    cloud_base_url = load_config(user_config).cloud.base_url

    workspace = REPO_ROOT / ".calibration_push" / device
    workspace.mkdir(parents=True, exist_ok=True)
    config_file = workspace / "config.toml"
    write_push_config(config_file, device, device_folder, cloud_base_url)

    cmd = [
        "uv", "run", "rock-paper-sync", "sync",
        "--config", str(config_file),
        "--direction", "push",
    ]
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=REPO_ROOT)
    if result.returncode != 0:
        print_error("Push failed. See sync log for details.")
        sys.exit(1)

    docs = corpus_documents(device)
    print_ok(f"Pushed {len(docs)} calibration documents into folder '{device_folder}'")


# --- Step 2: operator checklist -------------------------------------------


def count_sentinels(device: str) -> list[str]:
    """Return sorted list of unique ZEBRAnn sentinels across the corpus."""
    import re

    sentinels: set[str] = set()
    for md in src_dir(device).glob("*.md"):
        sentinels.update(re.findall(r"ZEBRA\d{2}", md.read_text()))
    return sorted(sentinels)


def print_checklist(device: str, device_folder: str) -> None:
    sentinels = count_sentinels(device)
    docs = corpus_documents(device)
    y = Colors.YELLOW
    b = Colors.BOLD
    e = Colors.END

    print(f"\n{b}{'=' * 70}{e}")
    print(f"{b}  OPERATOR CHECKLIST — do this on the device now{e}")
    print(f"{b}{'=' * 70}{e}")
    print(f"\nOpen the folder {y}{device_folder}{e} on the device. It contains "
          f"{len(docs)} documents:")
    for d in docs:
        print(f"    - {d}")
    print(f"\n{b}1. Highlight every sentinel token.{e}")
    print(f"   There are {y}{len(sentinels)}{e} sentinels: "
          f"{sentinels[0]}…{sentinels[-1]}.")
    print("   Use the highlighter tool. Drag over exactly the ZEBRAnn word so")
    print("   the highlight covers those glyphs and nothing else. One highlight")
    print("   per sentinel. Highlight ALL of them — a missed sentinel is a hole")
    print("   in the corpus.")
    print(f"\n{b}2. T5 baseline probe (document 07_t5_probe).{e}")
    print("   a. Highlight the token T5BASE at the start of the underscore line.")
    print("   b. With the PEN, draw a short vertical stroke starting on the")
    print("      baseline of the underscores and going downward (a descender),")
    print("      crossing the T5BASE marker.")
    print(f"\n{b}3. Sync the device{e} (let it push annotations back to the cloud).")
    print("   Confirm the highlights have uploaded before continuing.")
    print(f"\n{b}{'=' * 70}{e}")


# --- Step 3: pull ----------------------------------------------------------


def read_firmware_info(device_host: str) -> dict[str, str]:
    """Read firmware / xochitl version strings from the device via SSH."""
    info: dict[str, str] = {}
    probes = {
        "os_version": "cat /etc/version 2>/dev/null",
        "release_version": (
            "grep -h REMARKABLE_RELEASE_VERSION "
            "/usr/share/remarkable/update.conf 2>/dev/null | cut -d= -f2"
        ),
        "xochitl_version": "/usr/bin/xochitl --version 2>/dev/null | head -1",
    }
    for key, remote_cmd in probes.items():
        try:
            result = subprocess.run(
                ["ssh", f"root@{device_host}", remote_cmd],
                capture_output=True, text=True, timeout=20,
            )
            value = result.stdout.strip()
            if value:
                info[key] = value
        except Exception as exc:  # noqa: BLE001 - best-effort probe
            print_warn(f"Could not read {key}: {exc}")
    return info


def pull_corpus(device: str, device_host: str, device_folder: str) -> None:
    """Download recorded .rm files + thumbnails and stamp profile.json."""
    print_step("Pulling recorded corpus from device")

    _client, sync = get_cloud_client()

    out_root = corpus_dir(device)
    rm_root = out_root / "rm_files"
    rm_root.mkdir(parents=True, exist_ok=True)

    recorded: dict[str, list[str]] = {}
    for doc_name in corpus_documents(device):
        try:
            doc_uuid, resolved_name = find_document(sync, doc_name)
        except SystemExit:
            print_warn(f"Document not found on device: {doc_name} (skipping)")
            continue

        rm_files = download_rm_files(sync, doc_uuid)
        doc_dir = rm_root / doc_name
        doc_dir.mkdir(parents=True, exist_ok=True)
        for page_uuid, content in rm_files.items():
            (doc_dir / f"{page_uuid}.rm").write_bytes(content)

        # Thumbnails are a last-resort visual aid (P2); best-effort.
        try:
            thumbs = capture_thumbnails_via_ssh(device_host, doc_uuid)
            for page_uuid, png in thumbs.items():
                (doc_dir / f"{page_uuid}.png").write_bytes(png)
        except Exception as exc:  # noqa: BLE001
            print_warn(f"Thumbnail capture failed for {doc_name}: {exc}")

        recorded[doc_name] = sorted(rm_files.keys())
        print_ok(f"{doc_name}: {len(rm_files)} page(s) from '{resolved_name}'")

    firmware = read_firmware_info(device_host)
    stamp_profile(device, firmware, recorded)


def stamp_profile(device: str, firmware: dict[str, str], recorded: dict[str, list[str]]) -> None:
    """Write recording provenance into profile.json (measurements come later).

    This only records the *session* metadata (firmware, date, which documents
    were captured). Measured layout values are filled in by
    ``extract_profile.py``, which reads this file and augments it.
    """
    import json
    from datetime import datetime, timezone

    profile_path = corpus_dir(device) / "profile.json"
    profile: dict = {}
    if profile_path.exists():
        profile = json.loads(profile_path.read_text())

    profile["device_name"] = device
    profile.setdefault("page_width", 1404)
    profile.setdefault("page_height", 1872)
    recording = {
        "recorded_date": datetime.now(timezone.utc).isoformat()[:10],
        "firmware": firmware or None,
        "documents": recorded,
    }
    profile["recording"] = recording
    profile["golden_files"] = [f"rm_files/{name}" for name in sorted(recorded)]

    profile_path.write_text(json.dumps(profile, indent=2) + "\n")
    print_ok(f"Stamped recording provenance into {profile_path}")
    if not firmware:
        print_warn("Firmware version could not be read; 'firmware' is null. "
                   "Fill it in manually before committing (spec requires it).")


# --- main ------------------------------------------------------------------


def main() -> None:
    from rock_paper_sync.rm_cloud_client import RmCloudClient  # noqa: F401  (import check)

    parser = argparse.ArgumentParser(
        description="Record the layout ground-truth corpus in one device session.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--device", default=DEFAULT_DEVICE,
                        help=f"Device name / corpus subdir (default: {DEFAULT_DEVICE})")
    parser.add_argument("--device-host", default="remarkable-ppm",
                        help="SSH hostname of the device (default: remarkable-ppm)")
    parser.add_argument("--device-folder", default=DEFAULT_DEVICE_FOLDER,
                        help=f"Folder on device (default: {DEFAULT_DEVICE_FOLDER})")
    parser.add_argument("--user-config",
                        default=Path.home() / ".config" / "rock-paper-sync" / "config.toml",
                        type=Path, help="Cloud config for push")
    parser.add_argument("--skip-push", action="store_true",
                        help="Skip push; go straight to checklist + pull")
    parser.add_argument("--push-only", action="store_true",
                        help="Push and print checklist, then stop (pull later)")
    parser.add_argument("--pull-only", action="store_true",
                        help="Skip push and checklist; only pull recorded files")
    args = parser.parse_args()

    if not src_dir(args.device).exists():
        print_error(f"Corpus source not found: {src_dir(args.device)}")
        sys.exit(1)

    if args.pull_only:
        pull_corpus(args.device, args.device_host, args.device_folder)
        return

    if not args.skip_push:
        push_corpus(args.device, args.device_folder, args.user_config)

    print_checklist(args.device, args.device_folder)

    if args.push_only:
        print("\nRe-run with --pull-only once annotations are synced to pull the corpus.")
        return

    input(f"\n{Colors.YELLOW}Press Enter once all sentinels are highlighted and "
          f"synced to the cloud...{Colors.END}")

    pull_corpus(args.device, args.device_host, args.device_folder)
    print_step("Done. Next: uv run python tools/calibration/extract_profile.py "
               f"--device {args.device} "
               f"--input {corpus_dir(args.device)} "
               f"--output {corpus_dir(args.device) / 'profile.json'}")


if __name__ == "__main__":
    main()
